src/Entity/Pedido.php
<?php

namespace App\Entity;

use App\Repository\PedidoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PedidoRepository::class)]
class Pedido
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'pedidos')]
    private ?Cliente $Usuario = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $fecha_pedido = null;

    /**
     * @var Collection<int, ListaProductos>
     */
    #[ORM\OneToMany(targetEntity: ListaProductos::class, mappedBy: 'Pedido', cascade: ['persist', 'remove'])]
    private Collection $lista;

    public function __construct()
    {
        $this->lista = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsuario(): ?Cliente
    {
        return $this->Usuario;
    }

    public function setUsuario(?Cliente $Usuario): static
    {
        $this->Usuario = $Usuario;

        return $this;
    }

    public function getFechaPedido(): ?\DateTimeInterface
    {
        return $this->fecha_pedido;
    }

    public function setFechaPedido(\DateTimeInterface $fecha_pedido): static
    {
        $this->fecha_pedido = $fecha_pedido;

        return $this;
    }

    /**
     * @return Collection<int, ListaProductos>
     */
    public function getLista(): Collection
    {
        return $this->lista;
    }

    public function addListaProducto(ListaProductos $listaProducto): static
    {
        if (!$this->lista->contains($listaProducto)) {
            $this->lista->add($listaProducto);
            $listaProducto->setPedido($this);
        }

        return $this;
    }

    public function removeListaProducto(ListaProductos $listaProducto): static
    {
        if ($this->lista->removeElement($listaProducto)) {
            // set the owning side to null (unless already changed)
            if ($listaProducto->getPedido() === $this) {
                $listaProducto->setPedido(null);
            }
        }

        return $this;
    }
}

src/Entity/Producto.php
<?php

namespace App\Entity;

use App\Repository\ProductoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductoRepository::class)]
class Producto
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nombre = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Descripcion = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $Precio = null;

    /**
     * @var Collection<int, ListaProductos>
     */
    #[ORM\ManyToMany(targetEntity: ListaProductos::class, mappedBy: 'Articulo')]
    private Collection $listaProductos;

    public function __construct()
    {
        $this->listaProductos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): static
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->Descripcion;
    }

    public function setDescripcion(string $Descripcion): static
    {
        $this->Descripcion = $Descripcion;

        return $this;
    }

    public function getPrecio(): ?string
    {
        return $this->Precio;
    }

    public function setPrecio(string $Precio): static
    {
        $this->Precio = $Precio;

        return $this;
    }

    /**
     * @return Collection<int, ListaProductos>
     */
    public function getListaProductos(): Collection
    {
        return $this->listaProductos;
    }

    public function addListaProducto(ListaProductos $listaProducto): static
    {
        if (!$this->listaProductos->contains($listaProducto)) {
            $this->listaProductos->add($listaProducto);
            $listaProducto->addArticulo($this);
        }

        return $this;
    }

    public function removeListaProducto(ListaProductos $listaProducto): static
    {
        if ($this->listaProductos->removeElement($listaProducto)) {
            $listaProducto->removeArticulo($this);
        }

        return $this;
    }
}

src/Form/PedidoType.php
<?php

namespace App\Form;

use App\Entity\Cliente;
use App\Entity\ListaProductos;
use App\Entity\Pedido;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PedidoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('fecha_pedido', null, [
                'widget' => 'single_text',
            ])
            ->add('Usuario', EntityType::class, [
                'class' => Cliente::class,
                'choice_label' => 'username',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Pedido::class,
        ]);
    }
}

src/Controller/PedidoController.php
<?php

namespace App\Controller;

use App\Entity\Pedido;
use App\Entity\ListaProductos;
use App\Form\PedidoType;
use App\Repository\PedidoRepository;
use App\Repository\ProductoRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/pedido')]
class PedidoController extends AbstractController
{
    #[Route('/', name: 'app_pedido_index', methods: ['GET'])]
    public function index(PedidoRepository $pedidoRepository): Response
    {
        return $this->render('pedido/index.html.twig', [
            'pedidos' => $pedidoRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_pedido_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, ProductoRepository $productoRepository): Response
    {
        $pedido = new Pedido();
        $form = $this->createForm(PedidoType::class, $pedido);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data = $request->request->all();
            foreach ($data['productos'] as $productoId => $cantidad) {
                $producto = $productoRepository->find($productoId);
                if ($producto && $cantidad > 0) {
                    $listaProducto = new ListaProductos();
                    $listaProducto->setProducto($producto);
                    $listaProducto->setCantidad($cantidad);
                    $pedido->addListaProducto($listaProducto);
                    $entityManager->persist($listaProducto);
                }
            }

            $entityManager->persist($pedido);
            $entityManager->flush();

            return $this->redirectToRoute('app_pedido_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('pedido/new.html.twig', [
            'pedido' => $pedido,
            'form' => $form->createView(),
            'productos' => $productoRepository->findAll(),
        ]);
    }

    #[Route('/{id}', name: 'app_pedido_show', methods: ['GET'])]
    public function show(Pedido $pedido): Response
    {
        return $this->render('pedido/show.html.twig', [
            'pedido' => $pedido,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_pedido_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Pedido $pedido, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PedidoType::class, $pedido);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_pedido_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('pedido/edit.html.twig', [
            'pedido' => $pedido,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_pedido_delete', methods: ['POST'])]
    public function delete(Request $request, Pedido $pedido, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $pedido->getId(), $request->request->get('_token'))) {
            $entityManager->remove($pedido);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_pedido_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/pedido/_delete_form.html.twig
<form method="post" action="{{ path('app_pedido_delete', {'id': pedido.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ pedido.id) }}">
    <button class="btn">Delete</button>
</form>

templates/pedido/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/pedido/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Pedido{% endblock %}

{% block body %}
    <h1>Edit Pedido</h1>

    {{ include('pedido/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_pedido_index') }}">back to list</a>

    {{ include('pedido/_delete_form.html.twig') }}
{% endblock %}

templates/pedido/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pedido index{% endblock %}

{% block body %}
    <h1>Pedido index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Fecha_pedido</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for pedido in pedidos %}
            <tr>
                <td>{{ pedido.id }}</td>
                <td>{{ pedido.fechaPedido ? pedido.fechaPedido|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_pedido_show', {'id': pedido.id}) }}">show</a>
                    <a href="{{ path('app_pedido_edit', {'id': pedido.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_pedido_new') }}">Create new</a>
{% endblock %}

templates/pedido/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Nuevo Pedido</h1>
    {{ form_start(form) }}
    {{ form_row(form.fecha_pedido) }}
    {{ form_row(form.Usuario) }}

    <label for="productos">Productos</label>
    {% for producto in productos %}
        <div>
            <label>{{ producto.nombre }}</label>
            <input type="number" name="productos[{{ producto.id }}]" value="0" min="0">
        </div>
    {% endfor %}

    <button class="btn">Hacer Pedido</button>
    {{ form_end(form) }}
{% endblock %}

templates/pedido/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pedido{% endblock %}

{% block body %}
    <h1>Pedido</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ pedido.id }}</td>
            </tr>
            <tr>
                <th>Fecha_pedido</th>
                <td>{{ pedido.fechaPedido ? pedido.fechaPedido|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_pedido_index') }}">back to list</a>

    <a href="{{ path('app_pedido_edit', {'id': pedido.id}) }}">edit</a>

    {{ include('pedido/_delete_form.html.twig') }}
{% endblock %}